
# version: 1.0 # do not change
# should i use a separate yaml file for each version update (config.v1.yml)

settings:
  port: 8888 # server port (select an unused port above 1023)
  interval: 100 # browser polling timeout in milliseconds
  exit: 255 # lf requires a non-zero return value to disable caching

  # browser: # command to start the browser
  # auto_start:  true # cannon <file> will start the server automatically
  # cache_count: 16   # precache this many files in the background
  # proc_count:  4    # do this many conversions concurrently

file_conversion_rules:
  -
    # native html5 image formats do not need any conversion
    type: extension
    matches: [apng,avif,gif,jpg,jpeg,jfif,pjpeg,pjp,png,svg,webp]
    tag: <img id="{{.id}}" src="{{.src}}">
  -
    # convert other image formats to jpg using imagemagick
    # $ convert identify -list format | less
    type: extension
    matches: [bmp,ico,cur,tif,tiff]
    command: convert ${INPUT} ${OUTPUT}.jpg
    tag: img
  -
    # convert pdf 1st page to jpg using imagemagick
    type: extension
    matches: [pdf]
    command: convert -density 150 ${INPUT}[0] -quality 90 ${OUTPUT}.jpg
    tag: img
  -
    type: mime
    matches: [application/text]
    command: more t.txt
    tag: head
