
settings:
  port: 8888

file_conversion_rules:
  -
    type: extension
    matches: [mp3,pdf]
    tag: hostname
  -
    type: extension
    matches: [mov]
    command: whereis emacs
    tag: blabla-hostname
  -
    type: extension
    matches: [mp4, jpg]
    command: ls -alg
    tag: video
  -
    type: mime
    matches: [application/text]
    command: more t.txt
    tag: head

